[package]
name = "pgp-info-card"
version = "0.1.0"
entrypoint = "lib.typ"
authors = ["ak1ra <git@ak1ra.xyz>"]
license = "MIT"
description = "Printable OpenPGP keysigning party card with QR code."
repository = "https://github.com/ak1ra-lab/pgp-info-card"
keywords = ["openpgp", "pgp", "gpg", "keysigning", "qr code", "business card"]
categories = ["office"]
compiler = "0.13.0"

[template]
path = "template"
entrypoint = "main.typ"
thumbnail = "thumbnail.png"
